# Generated by Django 6.0 on 2025-12-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a terminé le parcours d'onboarding", verbose_name='onboarding complété'),
        ),
    ]
