# Generated by Django 6.0 on 2025-12-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_onboarding_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('mentor', 'Mentor'), ('student', 'Étudiant')], max_length=10, null=True),
        ),
    ]
