# Generated by Django 6.0 on 2025-12-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_alter_studentprofile_github_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
    ]
