# Generated by Django 6.0 on 2025-12-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0003_mentorprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la matière')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (optionnel)", max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interests_old',
            field=models.CharField(blank=True, help_text='Ancien champ - à supprimer après migration', max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='students', to='mentoring.subject', verbose_name="Centres d'intérêt"),
        ),
    ]
