# Generated by Django 6.0 on 2025-12-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0004_subject_studentprofile_interests_old_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoringsession',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('scheduled', 'Confirmée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('rejected', 'Refusée')], default='pending', max_length=20),
        ),
    ]
