# Generated by Django 5.1.7 on 2025-12-21 (Manual creation)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0005_alter_mentoringsession_status'),
    ]

    operations = [
        # Rendre le champ student nullable
        migrations.AlterField(
            model_name='mentoringsession',
            name='student',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mentoring_sessions',
                to='mentoring.studentprofile'
            ),
        ),
        # Ajouter le nouveau statut 'available'
        migrations.AlterField(
            model_name='mentoringsession',
            name='status',
            field=models.CharField(
                choices=[
                    ('available', 'Disponible'),
                    ('pending', 'En attente'),
                    ('scheduled', 'Confirmée'),
                    ('in_progress', 'En cours'),
                    ('completed', 'Terminée'),
                    ('cancelled', 'Annulée'),
                    ('rejected', 'Refusée')
                ],
                default='pending',
                max_length=20
            ),
        ),
    ]
