# Generated by Django 5.2.1 on 2025-05-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mentorprofile_studentprofile'),
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoringsession',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_sessions', to='accounts.mentorprofile'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.mentorprofile'),
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='mentoringsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_sessions', to='accounts.studentprofile'),
        ),
        migrations.DeleteModel(
            name='MentorProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
